kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: shmolyneaux/ziglang
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
        - VERSION=0.8.0
    tags:
        - "0.8.0"

trigger:
  event:
  - push
