kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: shmolyneaux/ziglang
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
        - DEV_BUILD=0.9.0-dev.1139+affd8f8b5
        # Dev builds take preference
        #- VERSION=0.8.0
    tags:
        - "0.9.0-dev.1139"

trigger:
  event:
  - push
